/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../../../index.js";

export interface CreateAgentTextAssetResponse extends Sonyk.BaseResponse {
    data?: CreateAgentTextAssetResponse.Data;
}

export namespace CreateAgentTextAssetResponse {
    export interface Data {
        /** Unique identifier for the created asset */
        assetId?: number;
        /** Title of the created asset */
        title?: string;
        /** Asset type (always TEXT for text assets) */
        type?: "TEXT";
        /** Cloud storage URL for the content */
        url?: string;
        /** Length of the processed text in characters */
        textLength?: number;
        /** Number of searchable chunks created */
        chunkCount?: number;
        /** Processing details and configuration */
        processingInfo?: Data.ProcessingInfo;
    }

    export namespace Data {
        /**
         * Processing details and configuration
         */
        export interface ProcessingInfo {
            /** Target chunk size used for segmentation */
            chunkSize?: number;
            /** AI model used for vector embeddings */
            embeddingModel?: string;
            /** Processing time in seconds */
            processingTime?: number;
            /** Whether document structure (headings, Q&A) was detected */
            structureDetected?: boolean;
        }
    }
}
