/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ListAgentAssetsRequestType = "FILE" | "TEXT" | "TRAINING";
export const ListAgentAssetsRequestType = {
    File: "FILE",
    Text: "TEXT",
    Training: "TRAINING",
} as const;
