/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../../../index.js";

export interface UpdateAgentAssetResponse extends Sonyk.BaseResponse {
    data?: UpdateAgentAssetResponse.Data;
}

export namespace UpdateAgentAssetResponse {
    export interface Data {
        /** Number of new chunks created (if text was updated) */
        chunkCount?: number;
    }
}
