/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../../../index.js";

export interface UploadAgentAssetResponse extends Sonyk.BaseResponse {
    data?: UploadAgentAssetResponse.Data;
}

export namespace UploadAgentAssetResponse {
    export interface Data {
        /** Unique identifier for the created asset */
        assetId?: number;
        /** Final title of the asset */
        title?: string;
        /** Asset type (always FILE for uploads) */
        type?: "FILE";
        /** Cloud storage URL for the processed content */
        url?: string;
        /** Length of the extracted and processed text in characters */
        textLength?: number;
        /** Number of searchable text chunks created */
        chunkCount?: number;
        /** Original file size in bytes */
        fileSize?: number;
        /** Detailed information about the processing pipeline */
        processingInfo?: Data.ProcessingInfo;
    }

    export namespace Data {
        /**
         * Detailed information about the processing pipeline
         */
        export interface ProcessingInfo {
            /** Length of raw extracted text before AI enhancement */
            originalLength?: number;
            /** Length after AI-powered text cleaning and enhancement */
            sanitizedLength?: number;
            /** Target chunk size used for segmentation */
            chunkSize?: number;
            /** AI model used for generating vector embeddings */
            embeddingModel?: string;
            /** Whether AI text enhancement was applied */
            sanitizationApplied?: boolean;
            /** Processing time in seconds */
            processingTime?: number;
        }
    }
}
