/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         text: "# Customer Service FAQ - Updated January 2025\n\n## Business Information\n\n### Q: What are your business hours?\nA: We are open Monday to Friday from 9 AM to 6 PM EST. Weekend support is available via email only.\n\n### Q: Where are you located?\nA: Our headquarters is at 123 Business St, City, State 12345. We also have locations in Chicago and Miami.\n\n## Product Support\n\n### Q: How do I return a product?\nA: Returns are easy! Visit our website's return portal, print a shipping label, and send the item back within 30 days. Refunds are processed within 5-7 business days.\n\n### Q: What's your warranty policy?\nA: All products come with a standard 1-year warranty. Extended warranties up to 3 years are available for purchase.\n\n## Account Management\n\n### Q: How do I reset my password?\nA: Click 'Forgot Password' on the login page, enter your email, and follow the instructions sent to your inbox. The reset link expires in 24 hours.\n\n### Q: Can I change my subscription plan?\nA: Yes! Log into your account, go to Settings > Subscription, and select your new plan. Changes take effect immediately.\n"
 *     }
 */
export interface CreateAgentTextAssetRequest {
    /**
     * Descriptive title for the text asset.
     *
     * **Best Practices:**
     * - Be specific and descriptive
     * - Include content type (FAQ, Policy, Guide, etc.)
     * - Add version numbers for updates
     * - Use consistent naming conventions
     */
    title?: string;
    /**
     * The text content to add to the agent's knowledge base.
     *
     * **Content Requirements:**
     * - Minimum 10 characters (ensures meaningful content)
     * - Maximum 50,000 characters (optimal for processing)
     * - UTF-8 encoding supported (multi-language content)
     * - Markdown formatting recommended for structure
     *
     * **Formatting Tips:**
     * - Use # for main headings, ## for subheadings
     * - Structure Q&A with clear question and answer sections
     * - Use bullet points for lists and features
     * - Include examples and specific details
     */
    text: string;
}
