/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../../../../index.js";

/**
 * @example
 *     {
 *         search: "product documentation"
 *     }
 */
export interface ListAgentAssetsRequest {
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of items per page
     */
    limit?: number;
    /**
     * Filter by asset type
     */
    type?: Sonyk.ListAgentAssetsRequestType;
    /**
     * Search assets by title or content
     */
    search?: string;
}
