/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         query: "How do I reset my password?"
 *     }
 */
export interface SearchAgentAssetsRequest {
    /** Search query for finding relevant content */
    query: string;
    /** Maximum number of results to return */
    limit?: number;
    /**
     * Minimum similarity score for results (0.0 = any match, 1.0 = perfect match).
     * Higher values return fewer, more relevant results.
     */
    threshold?: number;
    /** Filter results by chunk type (optional) */
    type?: SearchAgentAssetsRequest.Type;
}

export namespace SearchAgentAssetsRequest {
    /**
     * Filter results by chunk type (optional)
     */
    export type Type = "DOCUMENT" | "TRAINING_Q" | "TRAINING_A";
    export const Type = {
        Document: "DOCUMENT",
        TrainingQ: "TRAINING_Q",
        TrainingA: "TRAINING_A",
    } as const;
}
