/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UpdateAgentAssetRequest {
    /** New title for the asset */
    title?: string;
    /**
     * Updated text content (TEXT assets only).
     *
     * **Requirements:**
     * - Minimum 10 characters
     * - Maximum 50,000 characters
     * - Only applies to TEXT type assets
     * - Triggers automatic reprocessing
     */
    text?: string;
}
