/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as fs from "fs";
import * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file")
 *     }
 */
export interface UploadAgentAssetRequest {
    file: core.file.Uploadable.FileLike;
    /**
     * Optional custom title for the asset.
     * If not provided, the filename will be used.
     *
     * **Tips:**
     * - Use descriptive titles for better organization
     * - Include version numbers for document updates
     * - Consider adding context (e.g., "Product Manual v2.1")
     */
    title?: string;
}
