/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListToolsRequest {
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of items per page
     */
    limit?: number;
    /**
     * Search tools by name or description
     */
    search?: string;
}
