/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SetProviderKeyRequestProvider = "groq" | "openai" | "cartesia" | "deepgram" | "anthropic" | "elevenlabs";
export const SetProviderKeyRequestProvider = {
    Groq: "groq",
    Openai: "openai",
    Cartesia: "cartesia",
    Deepgram: "deepgram",
    Anthropic: "anthropic",
    Elevenlabs: "elevenlabs",
} as const;
