/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index.js";
import * as Sonyk from "../index.js";
import * as core from "../../core/index.js";

export class UnprocessableEntityError extends errors.SonykError {
    constructor(body: Sonyk.ErrorResponse, rawResponse?: core.RawResponse) {
        super({
            message: "UnprocessableEntityError",
            statusCode: 422,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, UnprocessableEntityError.prototype);
    }
}
