/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         toolId: "tool_123abc456def"
 *     }
 */
export interface AssignToolToAgentRequest {
    /** Tool identifier to assign */
    toolId: string;
}
