/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../../../../index.js";

/**
 * @example
 *     {
 *         agent_name: "Restaurant Receptionist",
 *         agent_json: {
 *             llm: {
 *                 provider: "sonyk",
 *                 model: "sonyk-llm",
 *                 systemPrompt: "You are Georgia, a friendly and professional receptionist at the  restaurant.\n"
 *             },
 *             stt: {
 *                 provider: "sonyk",
 *                 model: "sonyk-stt",
 *                 language: "en"
 *             },
 *             tts: {
 *                 provider: "sonyk",
 *                 model: "sonyk-tts",
 *                 voiceId: "indigo-sonyk"
 *             },
 *             firstMessage: "Hello! Welcome to  restaurant. I am Georgia, how can I help you today?"
 *         }
 *     }
 */
export interface CreateAgentRequest {
    /** Human-readable name for the agent */
    agent_name: string;
    agent_json: Sonyk.AgentConfiguration;
}
