/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateAgentRequest {
    agent_name?: string;
    agent_json?: Sonyk.AgentConfiguration;
}
