/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         phoneNumber: "+1234567890",
 *         provider: "twilio"
 *     }
 */
export interface CreatePhoneRequest {
    /** Phone number in E.164 format */
    phoneNumber: string;
    /** Phone service provider */
    provider: string;
    /** Optional friendly name for the phone */
    nickname?: string;
    /** Optional agent to assign the phone to */
    agentId?: string;
}
