/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         provider: "twilio"
 *     }
 */
export interface ListPhonesRequest {
    /**
     * Page number for pagination
     */
    page?: number;
    /**
     * Number of items per page
     */
    limit?: number;
    /**
     * Filter by phone provider
     */
    provider?: string;
    /**
     * Filter by active status
     */
    is_active?: boolean;
    /**
     * Filter by assigned agent
     */
    agentId?: string;
}
