/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         agentId: "agentId"
 *     }
 */
export interface MapPhoneToAgentRequest {
    /** Agent ID to assign the phone to */
    agentId: string;
}
