/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UpdatePhoneRequest {
    nickname?: string;
    /** Agent ID to assign (null to unassign) */
    agentId?: string;
    isActive?: boolean;
}
