/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

/**
 * Large Language Model configuration that powers the agent's conversational abilities.
 * This is the "brain" of your agent that processes user input and generates responses.
 */
export type AgentConfigurationLlm =
    | Sonyk.AgentConfigurationLlm.Openai
    | Sonyk.AgentConfigurationLlm.Anthropic
    | Sonyk.AgentConfigurationLlm.Groq;

export namespace AgentConfigurationLlm {
    export interface Openai extends Sonyk.OpenAillm {
        provider: "openai";
    }

    export interface Anthropic extends Sonyk.AnthropicLlm {
        provider: "anthropic";
    }

    export interface Groq extends Sonyk.GroqLlm {
        provider: "groq";
    }
}
