/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

/**
 * Text-to-Speech configuration that controls how the agent's voice sounds.
 * This determines the personality and quality of the agent's speech.
 */
export type AgentConfigurationTts =
    | Sonyk.AgentConfigurationTts.Elevenlabs
    | Sonyk.AgentConfigurationTts.Cartesia
    | Sonyk.AgentConfigurationTts.Groq;

export namespace AgentConfigurationTts {
    export interface Elevenlabs extends Sonyk.ElevenLabsTts {
        provider: "elevenlabs";
    }

    export interface Cartesia extends Sonyk.CartesiaTts {
        provider: "cartesia";
    }

    export interface Groq extends Sonyk.GroqTts {
        provider: "groq";
    }
}
