/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

/**
 * Complete configuration object for an AI voice agent. This JSON structure defines
 * all aspects of the agent's behavior, voice characteristics, and integrations.
 *
 * ## Key Components:
 *
 * ### LLM (Large Language Model)
 * Controls the agent's conversational intelligence and reasoning capabilities.
 *
 * ### STT (Speech-to-Text)
 * Handles voice recognition and transcription of caller speech.
 *
 * ### TTS (Text-to-Speech)
 * Manages voice synthesis and how the agent sounds to callers.
 *
 * ### Behavior Settings
 * Defines conversation flow, greetings, and interaction patterns.
 */
export interface AgentConfiguration {
    /**
     * Large Language Model configuration that powers the agent's conversational abilities.
     * This is the "brain" of your agent that processes user input and generates responses.
     */
    llm: Sonyk.AgentConfigurationLlm;
    /**
     * Speech-to-Text configuration that converts caller voice to text.
     * This determines how accurately the agent understands what callers say.
     */
    stt: Sonyk.AgentConfigurationStt;
    /**
     * Text-to-Speech configuration that controls how the agent's voice sounds.
     * This determines the personality and quality of the agent's speech.
     */
    tts: Sonyk.AgentConfigurationTts;
    /** Display name for the agent (for your reference) */
    name: string;
    /**
     * **Critical Setting**: The first thing your agent says when someone calls.
     * This sets the tone for the entire conversation.
     *
     * **Tips:**
     * - Keep it friendly and professional
     * - Clearly identify who/what the agent represents
     * - Ask how you can help
     * - Keep it under 20 words for best experience
     */
    firstMessage: string;
    /**
     * Optional webhook URL to receive call events and data.
     * Your server will receive POST requests with:
     * - Call transcripts
     * - Call summaries
     * - Call duration and costs
     * - Custom data from tool executions
     */
    webhookUrl?: string;
    /**
     * Optional phone number to forward calls to if the agent cannot handle them.
     * Useful for escalation or human handoff.
     */
    callForwardNumber?: string;
    /**
     * Schema definition for structured data extraction from calls.
     * This defines what data should be captured and returned after each call.
     */
    structuredDataSchema?: AgentConfiguration.StructuredDataSchema;
}

export namespace AgentConfiguration {
    /**
     * Schema definition for structured data extraction from calls.
     * This defines what data should be captured and returned after each call.
     */
    export interface StructuredDataSchema {
        /** Array of tags to categorize the call */
        tags: string[];
        /** Type/category of the call */
        call_type: StructuredDataSchema.CallType;
        /** Brief summary of the call content */
        call_summary: string;
        /** Whether to send menu/dish information via SMS */
        sendMenuDishSMS?: boolean;
        /** Reason if the call was transferred to a human */
        reasonOfCallTransfer?: string;
        /** Accepts any additional properties */
        [key: string]: any;
    }

    export namespace StructuredDataSchema {
        /**
         * Type/category of the call
         */
        export type CallType =
            | "Reservation"
            | "Takeaway"
            | "Delivery"
            | "Walk-in"
            | "Enquiry"
            | "Information"
            | "Other";
        export const CallType = {
            Reservation: "Reservation",
            Takeaway: "Takeaway",
            Delivery: "Delivery",
            WalkIn: "Walk-in",
            Enquiry: "Enquiry",
            Information: "Information",
            Other: "Other",
        } as const;
    }
}
