/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

/**
 * Speech-to-Text configuration that converts caller voice to text.
 * This determines how accurately the agent understands what callers say.
 */
export type AgentConfigurationStt = Sonyk.AgentConfigurationStt.Deepgram;

export namespace AgentConfigurationStt {
    export interface Deepgram extends Sonyk.DeepgramStt {
        provider: "deepgram";
    }
}
