/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface Agent {
    /** Unique agent identifier */
    agent_id?: string;
    /** Human-readable agent name */
    agent_name?: string;
    agent_json?: Sonyk.AgentConfiguration;
    /** Agent creation timestamp */
    created_at?: string;
    /** Organization ID that owns this agent */
    fk_org_id?: number;
}
