/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface AgentDetailed extends Sonyk.Agent {
    /** Knowledge base assets associated with the agent */
    assets?: Sonyk.Asset[];
    /** Phone numbers assigned to this agent */
    phones?: Sonyk.Phone[];
    /** Tools/functions available to this agent */
    tools?: Sonyk.Tool[];
}
