/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Anthropic Claude language model configuration
 */
export interface AnthropicLlm {
    /**
     * Anthropic Claude model to use:
     * - **claude-opus-4**: Most capable Claude model
     * - **claude-sonnet-4**: Excellent for detailed, nuanced conversations
     * - **claude-3-5-sonnet**: Previous generation, still very capable
     * - **claude-3-haiku**: Fast and efficient
     */
    model: AnthropicLlm.Model;
    /** **Most Important Setting**: This defines your agent's personality, knowledge, and behavior. */
    systemPrompt: string;
}

export namespace AnthropicLlm {
    /**
     * Anthropic Claude model to use:
     * - **claude-opus-4**: Most capable Claude model
     * - **claude-sonnet-4**: Excellent for detailed, nuanced conversations
     * - **claude-3-5-sonnet**: Previous generation, still very capable
     * - **claude-3-haiku**: Fast and efficient
     */
    export type Model =
        | "claude-3-opus-20240229"
        | "claude-3-sonnet-20240229"
        | "claude-3-haiku-20240307"
        | "claude-3-5-sonnet-20240620"
        | "claude-3-5-sonnet-20241022"
        | "claude-3-5-haiku-20241022"
        | "claude-3-7-sonnet-20250219"
        | "claude-opus-4-20250514"
        | "claude-sonnet-4-20250514";
    export const Model = {
        Claude3Opus20240229: "claude-3-opus-20240229",
        Claude3Sonnet20240229: "claude-3-sonnet-20240229",
        Claude3Haiku20240307: "claude-3-haiku-20240307",
        Claude35Sonnet20240620: "claude-3-5-sonnet-20240620",
        Claude35Sonnet20241022: "claude-3-5-sonnet-20241022",
        Claude35Haiku20241022: "claude-3-5-haiku-20241022",
        Claude37Sonnet20250219: "claude-3-7-sonnet-20250219",
        ClaudeOpus420250514: "claude-opus-4-20250514",
        ClaudeSonnet420250514: "claude-sonnet-4-20250514",
    } as const;
}
