/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApiKeyStats {
    /** Total number of API keys */
    total_keys?: number;
    /** Number of active API keys */
    active_keys?: number;
    /** Total usage count across all keys */
    total_usage?: number;
    /** Number of expired API keys */
    expired_keys?: number;
}
