/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface ApiKeyCreatedResponse extends Sonyk.BaseResponse {
    data?: ApiKeyCreatedResponse.Data;
}

export namespace ApiKeyCreatedResponse {
    export interface Data {
        /** API key ID */
        id?: number;
        /** API key name */
        name?: string;
        /** The actual API key (only shown once) */
        apiKey?: string;
        organization?: Data.Organization;
        expiresAt?: string;
        permissions?: Record<string, unknown>;
        message?: string;
    }

    export namespace Data {
        export interface Organization {
            id?: number;
            name?: string;
        }
    }
}
