/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApiKey {
    /** API key ID */
    pk_api_key_id?: number;
    /** Descriptive name for the API key */
    api_key_name?: string;
    created_at?: string;
    last_used_at?: string;
    is_active?: boolean;
    expires_at?: string;
    /** API key permissions */
    permissions?: Record<string, unknown>;
    /** Number of times the key has been used */
    usage_count?: number;
    creator?: ApiKey.Creator;
}

export namespace ApiKey {
    export interface Creator {
        pk_user_id?: number;
        name?: string;
        email?: string;
    }
}
