/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssetChunk {
    /** Unique chunk identifier */
    pk_chunk_id?: number;
    /**
     * Type of content chunk:
     * - **DOCUMENT**: Regular document content
     * - **TRAINING_Q**: Training question
     * - **TRAINING_A**: Training answer
     */
    type?: AssetChunk.Type;
    /** The actual text content of this chunk */
    chunk_text?: string;
    /** When this chunk was created */
    date_created?: string;
}

export namespace AssetChunk {
    /**
     * Type of content chunk:
     * - **DOCUMENT**: Regular document content
     * - **TRAINING_Q**: Training question
     * - **TRAINING_A**: Training answer
     */
    export type Type = "DOCUMENT" | "TRAINING_Q" | "TRAINING_A";
    export const Type = {
        Document: "DOCUMENT",
        TrainingQ: "TRAINING_Q",
        TrainingA: "TRAINING_A",
    } as const;
}
