/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Asset {
    /** Unique asset identifier */
    pk_asset_id?: number;
    /** ID of the agent this asset belongs to */
    fk_agent_id?: string;
    /**
     * Type of asset:
     * - **FILE**: Uploaded document (PDF, DOCX, etc.)
     * - **TEXT**: Direct text input (FAQs, policies, etc.)
     * - **TRAINING**: Q&A pairs for agent training
     */
    type?: Asset.Type;
    /** Human-readable title for the asset */
    title?: string;
    /** Cloud storage URL for the processed text */
    url?: string;
    /** ID of the user who created this asset */
    fk_user_id?: number;
    /** When the asset was created */
    date_created?: string;
    /** Whether the asset is currently active */
    is_active?: boolean;
    /** Number of text chunks generated from this asset */
    chunk_count?: number;
}

export namespace Asset {
    /**
     * Type of asset:
     * - **FILE**: Uploaded document (PDF, DOCX, etc.)
     * - **TEXT**: Direct text input (FAQs, policies, etc.)
     * - **TRAINING**: Q&A pairs for agent training
     */
    export type Type = "FILE" | "TEXT" | "TRAINING";
    export const Type = {
        File: "FILE",
        Text: "TEXT",
        Training: "TRAINING",
    } as const;
}
