/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface AssetDetailed extends Sonyk.Asset {
    /** Text chunks generated from this asset (limited to first 20) */
    chunks?: Sonyk.AssetChunk[];
    /** User who created this asset */
    creator?: AssetDetailed.Creator;
}

export namespace AssetDetailed {
    /**
     * User who created this asset
     */
    export interface Creator {
        pk_user_id?: number;
        name?: string;
        email?: string;
    }
}
