/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Call {
    call_id?: string;
    call_dtm?: string;
    agent_id?: string;
    agent_name?: string;
    call_type?: Call.CallType;
    caller_phone_number?: string;
    agent_phone_number?: string;
    duration_sec?: number;
    call_end_reason?: string;
    call_purpose?: string;
    call_summary?: string;
    total_cost_usd?: number;
    credits_used?: number;
    duration_formatted?: string;
    tags?: string[];
    agent?: Call.Agent;
}

export namespace Call {
    export type CallType = "inbound" | "outbound";
    export const CallType = {
        Inbound: "inbound",
        Outbound: "outbound",
    } as const;

    export interface Agent {
        agent_id?: string;
        agent_name?: string;
        fk_org_id?: number;
    }
}
