/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Cartesia text-to-speech configuration
 */
export interface CartesiaTts {
    /**
     * Cartesia TTS model quality:
     * - **sonic-2**: Latest Cartesia model with improved quality
     * - **sonic-english**: Optimized for English
     * - **sonic-multilingual**: Multi-language support
     */
    model: CartesiaTts.Model;
    /** Cartesia voice configuration (depends on Cartesia's voice system) */
    voiceId: string;
}

export namespace CartesiaTts {
    /**
     * Cartesia TTS model quality:
     * - **sonic-2**: Latest Cartesia model with improved quality
     * - **sonic-english**: Optimized for English
     * - **sonic-multilingual**: Multi-language support
     */
    export type Model = "sonic-2" | "sonic-english" | "sonic-multilingual" | "sonic-preview" | "sonic";
    export const Model = {
        Sonic2: "sonic-2",
        SonicEnglish: "sonic-english",
        SonicMultilingual: "sonic-multilingual",
        SonicPreview: "sonic-preview",
        Sonic: "sonic",
    } as const;
}
