/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface CoreCallResponse extends Sonyk.BaseResponse {
    data?: CoreCallResponse.Data;
}

export namespace CoreCallResponse {
    export interface Data {
        core_response?: Record<string, unknown>;
        call_tracking?: Data.CallTracking;
        status_code?: number;
    }

    export namespace Data {
        export interface CallTracking {
            call_id?: string;
            agent_id?: string;
            to_number?: string;
            initiated_at?: string;
            estimated_credits?: number;
            available_credits?: number;
        }
    }
}
