/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateToolParameterRequest {
    /**
     * Parameter name that will be sent to your API.
     * Use snake_case format (e.g., customer_name, reservation_date).
     */
    param_name: string;
    /**
     * Data type of the parameter:
     * - **string**: Text values
     * - **integer**: Whole numbers
     * - **number**: Decimal numbers
     * - **boolean**: true/false values
     * - **array**: List of values
     * - **object**: Complex nested data
     */
    data_type: CreateToolParameterRequest.DataType;
    /** Whether this parameter must be provided */
    is_mandatory?: boolean;
    /**
     * Clear description of what this parameter represents.
     * The agent uses this to understand how to populate the parameter.
     */
    param_description: string;
}

export namespace CreateToolParameterRequest {
    /**
     * Data type of the parameter:
     * - **string**: Text values
     * - **integer**: Whole numbers
     * - **number**: Decimal numbers
     * - **boolean**: true/false values
     * - **array**: List of values
     * - **object**: Complex nested data
     */
    export type DataType = "string" | "integer" | "number" | "boolean" | "array" | "object";
    export const DataType = {
        String: "string",
        Integer: "integer",
        Number: "number",
        Boolean: "boolean",
        Array: "array",
        Object: "object",
    } as const;
}
