/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Deepgram speech-to-text configuration
 */
export interface DeepgramStt {
    /**
     * Deepgram STT model quality and speed:
     * - **nova-3**: Latest, most accurate (recommended)
     * - **nova-2**: Good balance of speed and accuracy
     * - **enhanced**: Enhanced accuracy model
     * - **base**: Faster but less accurate
     *
     * Specialized models available for different use cases:
     * - **nova-3-medical**: Optimized for medical terminology
     * - **nova-2-phonecall**: Optimized for phone call audio
     * - **nova-2-meeting**: Optimized for meeting recordings
     */
    model: DeepgramStt.Model;
    /**
     * Language code for speech recognition:
     * - **en**: English
     * - **es**: Spanish
     * - **fr**: French
     * - **de**: German
     * And many more...
     */
    language: string;
}

export namespace DeepgramStt {
    /**
     * Deepgram STT model quality and speed:
     * - **nova-3**: Latest, most accurate (recommended)
     * - **nova-2**: Good balance of speed and accuracy
     * - **enhanced**: Enhanced accuracy model
     * - **base**: Faster but less accurate
     *
     * Specialized models available for different use cases:
     * - **nova-3-medical**: Optimized for medical terminology
     * - **nova-2-phonecall**: Optimized for phone call audio
     * - **nova-2-meeting**: Optimized for meeting recordings
     */
    export type Model =
        | "nova-3"
        | "nova-3-general"
        | "nova-3-medical"
        | "nova-2"
        | "nova-2-general"
        | "nova-2-meeting"
        | "nova-2-phonecall"
        | "nova-2-finance"
        | "nova-2-conversationalai"
        | "nova-2-voicemail"
        | "nova-2-video"
        | "nova-2-medical"
        | "nova-2-drivethru"
        | "nova-2-automotive"
        | "nova"
        | "nova-general"
        | "nova-phonecall"
        | "nova-medical"
        | "enhanced"
        | "enhanced-general"
        | "enhanced-meeting"
        | "enhanced-phonecall"
        | "enhanced-finance"
        | "base"
        | "base-general"
        | "base-meeting"
        | "base-phonecall"
        | "base-finance"
        | "base-conversationalai"
        | "base-voicemail"
        | "base-video";
    export const Model = {
        Nova3: "nova-3",
        Nova3General: "nova-3-general",
        Nova3Medical: "nova-3-medical",
        Nova2: "nova-2",
        Nova2General: "nova-2-general",
        Nova2Meeting: "nova-2-meeting",
        Nova2Phonecall: "nova-2-phonecall",
        Nova2Finance: "nova-2-finance",
        Nova2Conversationalai: "nova-2-conversationalai",
        Nova2Voicemail: "nova-2-voicemail",
        Nova2Video: "nova-2-video",
        Nova2Medical: "nova-2-medical",
        Nova2Drivethru: "nova-2-drivethru",
        Nova2Automotive: "nova-2-automotive",
        Nova: "nova",
        NovaGeneral: "nova-general",
        NovaPhonecall: "nova-phonecall",
        NovaMedical: "nova-medical",
        Enhanced: "enhanced",
        EnhancedGeneral: "enhanced-general",
        EnhancedMeeting: "enhanced-meeting",
        EnhancedPhonecall: "enhanced-phonecall",
        EnhancedFinance: "enhanced-finance",
        Base: "base",
        BaseGeneral: "base-general",
        BaseMeeting: "base-meeting",
        BasePhonecall: "base-phonecall",
        BaseFinance: "base-finance",
        BaseConversationalai: "base-conversationalai",
        BaseVoicemail: "base-voicemail",
        BaseVideo: "base-video",
    } as const;
}
