/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ElevenLabs text-to-speech configuration
 */
export interface ElevenLabsTts {
    /**
     * ElevenLabs TTS model quality:
     * - **eleven_turbo_v2_5**: Latest, highest quality (recommended)
     * - **eleven_flash_v2_5**: Fast with good quality
     * - **eleven_multilingual_v2**: For multiple languages
     */
    model: ElevenLabsTts.Model;
    /**
     * ElevenLabs voice personality:
     * - **burt**: Professional male voice
     * - **marissa**: Friendly female voice
     * - **andrea**: Energetic female voice
     * - **sarah**: Professional female voice
     * - **phillip**: Calm male voice
     * - **steve**: Confident male voice
     * - **joseph**: Warm male voice
     * - **myra**: Cheerful female voice
     * - **paula**: Professional female voice
     * - **ryan**: Young male voice
     * - **drew**: Casual male voice
     * - **paul**: Mature male voice
     * - **mrb**: British male voice
     * - **matilda**: Young female voice
     * - **mark**: Deep male voice
     *
     * OR any custom ElevenLabs voice ID string
     * Test voices at: elevenlabs.io/voice-library
     */
    voiceId: string;
}

export namespace ElevenLabsTts {
    /**
     * ElevenLabs TTS model quality:
     * - **eleven_turbo_v2_5**: Latest, highest quality (recommended)
     * - **eleven_flash_v2_5**: Fast with good quality
     * - **eleven_multilingual_v2**: For multiple languages
     */
    export type Model =
        | "eleven_multilingual_v2"
        | "eleven_turbo_v2"
        | "eleven_turbo_v2_5"
        | "eleven_flash_v2"
        | "eleven_flash_v2_5"
        | "eleven_monolingual_v1";
    export const Model = {
        ElevenMultilingualV2: "eleven_multilingual_v2",
        ElevenTurboV2: "eleven_turbo_v2",
        ElevenTurboV25: "eleven_turbo_v2_5",
        ElevenFlashV2: "eleven_flash_v2",
        ElevenFlashV25: "eleven_flash_v2_5",
        ElevenMonolingualV1: "eleven_monolingual_v1",
    } as const;
}
