/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface ErrorResponse extends Sonyk.BaseResponse {
    data?: ErrorResponse.Data.Item[];
}

export namespace ErrorResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            field?: string;
            message?: string;
        }
    }
}
