/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Groq text-to-speech configuration
 */
export interface GroqTts {
    /**
     * Groq TTS models:
     * - **playai-tts**: High-quality TTS model for English speech generation
     * - **playai-tts-arabic**: High-quality TTS model for Arabic speech generation
     */
    model: GroqTts.Model;
    /**
     * Groq TTS voice configuration. Since Groq uses PlayAI models, voice options depend on the specific model:
     * - For **playai-tts**: English voice options
     * - For **playai-tts-arabic**: Arabic voice options
     *
     * Check Groq documentation for available voice IDs for each model.
     */
    voiceId?: string;
}

export namespace GroqTts {
    /**
     * Groq TTS models:
     * - **playai-tts**: High-quality TTS model for English speech generation
     * - **playai-tts-arabic**: High-quality TTS model for Arabic speech generation
     */
    export type Model = "playai-tts" | "playai-tts-arabic";
    export const Model = {
        PlayaiTts: "playai-tts",
        PlayaiTtsArabic: "playai-tts-arabic",
    } as const;
}
