/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Groq language model configuration
 */
export interface GroqLlm {
    /**
     * Groq model to use:
     * - **llama-3.3-70b-versatile**: Fast inference, good general performance
     * - **llama-3.1-405b-reasoning**: Large model for complex reasoning
     * - **deepseek-r1-distill-llama-70b**: Optimized reasoning model
     */
    model: GroqLlm.Model;
    /** **Most Important Setting**: This defines your agent's personality, knowledge, and behavior. */
    systemPrompt: string;
}

export namespace GroqLlm {
    /**
     * Groq model to use:
     * - **llama-3.3-70b-versatile**: Fast inference, good general performance
     * - **llama-3.1-405b-reasoning**: Large model for complex reasoning
     * - **deepseek-r1-distill-llama-70b**: Optimized reasoning model
     */
    export type Model =
        | "openai/gpt-oss-20b"
        | "openai/gpt-oss-120b"
        | "deepseek-r1-distill-llama-70b"
        | "llama-3.3-70b-versatile"
        | "llama-3.1-405b-reasoning"
        | "llama-3.1-8b-instant"
        | "llama3-8b-8192"
        | "llama3-70b-8192"
        | "gemma2-9b-it"
        | "meta-llama/llama-4-maverick-17b-128e-instruct"
        | "meta-llama/llama-4-scout-17b-16e-instruct"
        | "mistral-saba-24b"
        | "compound-beta"
        | "compound-beta-mini";
    export const Model = {
        OpenaiGptOss20B: "openai/gpt-oss-20b",
        OpenaiGptOss120B: "openai/gpt-oss-120b",
        DeepseekR1DistillLlama70B: "deepseek-r1-distill-llama-70b",
        Llama3370BVersatile: "llama-3.3-70b-versatile",
        Llama31405BReasoning: "llama-3.1-405b-reasoning",
        Llama318BInstant: "llama-3.1-8b-instant",
        Llama38B8192: "llama3-8b-8192",
        Llama370B8192: "llama3-70b-8192",
        Gemma29BIt: "gemma2-9b-it",
        MetaLlamaLlama4Maverick17B128EInstruct: "meta-llama/llama-4-maverick-17b-128e-instruct",
        MetaLlamaLlama4Scout17B16EInstruct: "meta-llama/llama-4-scout-17b-16e-instruct",
        MistralSaba24B: "mistral-saba-24b",
        CompoundBeta: "compound-beta",
        CompoundBetaMini: "compound-beta-mini",
    } as const;
}
