/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface InviteUserResponse extends Sonyk.BaseResponse {
    data?: InviteUserResponse.Data;
}

export namespace InviteUserResponse {
    export interface Data {
        user?: Sonyk.UserProfile;
        organization?: Data.Organization;
        role?: string;
        invited_by?: number;
        joined_at?: string;
    }

    export namespace Data {
        export interface Organization {
            id?: number;
            name?: string;
        }
    }
}
