/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface LoginResponse extends Sonyk.BaseResponse {
    data?: LoginResponse.Data;
}

export namespace LoginResponse {
    export interface Data {
        user?: Sonyk.UserProfile;
        defaultOrganization?: Data.DefaultOrganization;
        allOrganizations?: Sonyk.OrganizationMembership[];
        tokens?: Data.Tokens;
    }

    export namespace Data {
        export interface DefaultOrganization {
            id?: number;
            name?: string;
            subscription_status?: string;
            credits_balance?: number;
        }

        export interface Tokens {
            /** JWT token for API access */
            jwt?: string;
            /** Firebase token */
            firebase?: string;
        }
    }
}
