/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * OpenAI language model configuration
 */
export interface OpenAillm {
    /**
     * OpenAI model to use:
     * - **gpt-4o**: Most capable, best for complex reasoning
     * - **gpt-4o-mini**: Fast and cost-effective, good for most use cases
     * - **gpt-3.5-turbo**: Legacy model, still capable
     * - **o1**, **o3**: Advanced reasoning models
     * - **gpt-4.1**: Latest GPT-4 variant with improved performance
     */
    model: OpenAillm.Model;
    /**
     * **Most Important Setting**: This defines your agent's personality, knowledge, and behavior.
     *
     * Write this as detailed instructions that include:
     * - **Role**: Who is the agent? (receptionist, support agent, etc.)
     * - **Personality**: Friendly, professional, casual, etc.
     * - **Knowledge**: What does the agent know about?
     * - **Tasks**: What can the agent help with?
     * - **Guidelines**: How should it behave in different situations?
     */
    systemPrompt: string;
}

export namespace OpenAillm {
    /**
     * OpenAI model to use:
     * - **gpt-4o**: Most capable, best for complex reasoning
     * - **gpt-4o-mini**: Fast and cost-effective, good for most use cases
     * - **gpt-3.5-turbo**: Legacy model, still capable
     * - **o1**, **o3**: Advanced reasoning models
     * - **gpt-4.1**: Latest GPT-4 variant with improved performance
     */
    export type Model =
        | "gpt-5"
        | "gpt-5-mini"
        | "gpt-5-nano"
        | "gpt-4.1-2025-04-14"
        | "gpt-4.1-mini-2025-04-14"
        | "gpt-4.1-nano-2025-04-14"
        | "gpt-4.1"
        | "gpt-4.1-mini"
        | "gpt-4.1-nano"
        | "chat"
        | "gpt-4o-latest"
        | "o3"
        | "o3-mini"
        | "o4-mini"
        | "o1-mini"
        | "o1-mini-2024-09-12"
        | "gpt-4o-realtime-preview-2024-10-01"
        | "gpt-4o-realtime-preview-2024-12-17"
        | "gpt-4o-mini-realtime-preview-2024-12-17"
        | "gpt-4o-mini-2024-07-18"
        | "gpt-4o-mini"
        | "gpt-4o"
        | "gpt-4o-2024-05-13"
        | "gpt-4o-2024-08-06"
        | "gpt-4o-2024-11-20"
        | "gpt-4-turbo"
        | "gpt-4-turbo-2024-04-09"
        | "gpt-4-turbo-preview"
        | "gpt-4-0125-preview"
        | "gpt-4-1106-preview"
        | "gpt-4"
        | "gpt-4-0613"
        | "gpt-3.5-turbo"
        | "gpt-3.5-turbo-0125"
        | "gpt-3.5-turbo-1106"
        | "gpt-3.5-turbo-16k"
        | "gpt-3.5-turbo-0613"
        | "gpt-4.1-2025-04-14:westus"
        | "gpt-4.1-2025-04-14:eastus2"
        | "gpt-4.1-2025-04-14:eastus"
        | "gpt-4.1-2025-04-14:westus3"
        | "gpt-4.1-2025-04-14:northcentralus"
        | "gpt-4.1-2025-04-14:southcentralus"
        | "gpt-4.1-mini-2025-04-14:westus"
        | "gpt-4.1-mini-2025-04-14:eastus2"
        | "gpt-4.1-mini-2025-04-14:eastus"
        | "gpt-4.1-mini-2025-04-14:westus3"
        | "gpt-4.1-mini-2025-04-14:northcentralus"
        | "gpt-4.1-mini-2025-04-14:southcentralus"
        | "gpt-4.1-nano-2025-04-14:westus"
        | "gpt-4.1-nano-2025-04-14:eastus2"
        | "gpt-4.1-nano-2025-04-14:westus3"
        | "gpt-4.1-nano-2025-04-14:northcentralus"
        | "gpt-4.1-nano-2025-04-14:southcentralus"
        | "gpt-4o-2024-11-20:swedencentral"
        | "gpt-4o-2024-11-20:westus"
        | "gpt-4o-2024-11-20:eastus2"
        | "gpt-4o-2024-11-20:eastus"
        | "gpt-4o-2024-11-20:westus3"
        | "gpt-4o-2024-11-20:southcentralus"
        | "gpt-4o-2024-08-06:westus"
        | "gpt-4o-2024-08-06:westus3"
        | "gpt-4o-2024-08-06:eastus"
        | "gpt-4o-2024-08-06:eastus2"
        | "gpt-4o-2024-08-06:northcentralus"
        | "gpt-4o-2024-08-06:southcentralus"
        | "gpt-4o-mini-2024-07-18:westus"
        | "gpt-4o-mini-2024-07-18:westus3"
        | "gpt-4o-mini-2024-07-18:eastus"
        | "gpt-4o-mini-2024-07-18:eastus2"
        | "gpt-4o-mini-2024-07-18:northcentralus"
        | "gpt-4o-mini-2024-07-18:southcentralus"
        | "gpt-4o-2024-05-13:eastus2"
        | "gpt-4o-2024-05-13:eastus"
        | "gpt-4o-2024-05-13:northcentralus"
        | "gpt-4o-2024-05-13:southcentralus"
        | "gpt-4o-2024-05-13:westus3"
        | "gpt-4o-2024-05-13:westus"
        | "gpt-4-turbo-2024-04-09:eastus2"
        | "gpt-4-0125-preview:eastus"
        | "gpt-4-0125-preview:northcentralus"
        | "gpt-4-0125-preview:southcentralus"
        | "gpt-4-1106-preview:australia"
        | "gpt-4-1106-preview:canadaeast"
        | "gpt-4-1106-preview:france"
        | "gpt-4-1106-preview:india"
        | "gpt-4-1106-preview:norway"
        | "gpt-4-1106-preview:swedencentral"
        | "gpt-4-1106-preview:uk"
        | "gpt-4-1106-preview:westus"
        | "gpt-4-1106-preview:westus3"
        | "gpt-4-0613:canadaeast"
        | "gpt-3.5-turbo-0125:canadaeast"
        | "gpt-3.5-turbo-0125:northcentralus"
        | "gpt-3.5-turbo-0125:southcentralus"
        | "gpt-3.5-turbo-1106:canadaeast"
        | "gpt-3.5-turbo-1106:westus";
    export const Model = {
        Gpt5: "gpt-5",
        Gpt5Mini: "gpt-5-mini",
        Gpt5Nano: "gpt-5-nano",
        Gpt4120250414: "gpt-4.1-2025-04-14",
        Gpt41Mini20250414: "gpt-4.1-mini-2025-04-14",
        Gpt41Nano20250414: "gpt-4.1-nano-2025-04-14",
        Gpt41: "gpt-4.1",
        Gpt41Mini: "gpt-4.1-mini",
        Gpt41Nano: "gpt-4.1-nano",
        Chat: "chat",
        Gpt4OLatest: "gpt-4o-latest",
        O3: "o3",
        O3Mini: "o3-mini",
        O4Mini: "o4-mini",
        O1Mini: "o1-mini",
        O1Mini20240912: "o1-mini-2024-09-12",
        Gpt4ORealtimePreview20241001: "gpt-4o-realtime-preview-2024-10-01",
        Gpt4ORealtimePreview20241217: "gpt-4o-realtime-preview-2024-12-17",
        Gpt4OMiniRealtimePreview20241217: "gpt-4o-mini-realtime-preview-2024-12-17",
        Gpt4OMini20240718: "gpt-4o-mini-2024-07-18",
        Gpt4OMini: "gpt-4o-mini",
        Gpt4O: "gpt-4o",
        Gpt4O20240513: "gpt-4o-2024-05-13",
        Gpt4O20240806: "gpt-4o-2024-08-06",
        Gpt4O20241120: "gpt-4o-2024-11-20",
        Gpt4Turbo: "gpt-4-turbo",
        Gpt4Turbo20240409: "gpt-4-turbo-2024-04-09",
        Gpt4TurboPreview: "gpt-4-turbo-preview",
        Gpt40125Preview: "gpt-4-0125-preview",
        Gpt41106Preview: "gpt-4-1106-preview",
        Gpt4: "gpt-4",
        Gpt40613: "gpt-4-0613",
        Gpt35Turbo: "gpt-3.5-turbo",
        Gpt35Turbo0125: "gpt-3.5-turbo-0125",
        Gpt35Turbo1106: "gpt-3.5-turbo-1106",
        Gpt35Turbo16K: "gpt-3.5-turbo-16k",
        Gpt35Turbo0613: "gpt-3.5-turbo-0613",
        Gpt4120250414Westus: "gpt-4.1-2025-04-14:westus",
        Gpt4120250414Eastus2: "gpt-4.1-2025-04-14:eastus2",
        Gpt4120250414Eastus: "gpt-4.1-2025-04-14:eastus",
        Gpt4120250414Westus3: "gpt-4.1-2025-04-14:westus3",
        Gpt4120250414Northcentralus: "gpt-4.1-2025-04-14:northcentralus",
        Gpt4120250414Southcentralus: "gpt-4.1-2025-04-14:southcentralus",
        Gpt41Mini20250414Westus: "gpt-4.1-mini-2025-04-14:westus",
        Gpt41Mini20250414Eastus2: "gpt-4.1-mini-2025-04-14:eastus2",
        Gpt41Mini20250414Eastus: "gpt-4.1-mini-2025-04-14:eastus",
        Gpt41Mini20250414Westus3: "gpt-4.1-mini-2025-04-14:westus3",
        Gpt41Mini20250414Northcentralus: "gpt-4.1-mini-2025-04-14:northcentralus",
        Gpt41Mini20250414Southcentralus: "gpt-4.1-mini-2025-04-14:southcentralus",
        Gpt41Nano20250414Westus: "gpt-4.1-nano-2025-04-14:westus",
        Gpt41Nano20250414Eastus2: "gpt-4.1-nano-2025-04-14:eastus2",
        Gpt41Nano20250414Westus3: "gpt-4.1-nano-2025-04-14:westus3",
        Gpt41Nano20250414Northcentralus: "gpt-4.1-nano-2025-04-14:northcentralus",
        Gpt41Nano20250414Southcentralus: "gpt-4.1-nano-2025-04-14:southcentralus",
        Gpt4O20241120Swedencentral: "gpt-4o-2024-11-20:swedencentral",
        Gpt4O20241120Westus: "gpt-4o-2024-11-20:westus",
        Gpt4O20241120Eastus2: "gpt-4o-2024-11-20:eastus2",
        Gpt4O20241120Eastus: "gpt-4o-2024-11-20:eastus",
        Gpt4O20241120Westus3: "gpt-4o-2024-11-20:westus3",
        Gpt4O20241120Southcentralus: "gpt-4o-2024-11-20:southcentralus",
        Gpt4O20240806Westus: "gpt-4o-2024-08-06:westus",
        Gpt4O20240806Westus3: "gpt-4o-2024-08-06:westus3",
        Gpt4O20240806Eastus: "gpt-4o-2024-08-06:eastus",
        Gpt4O20240806Eastus2: "gpt-4o-2024-08-06:eastus2",
        Gpt4O20240806Northcentralus: "gpt-4o-2024-08-06:northcentralus",
        Gpt4O20240806Southcentralus: "gpt-4o-2024-08-06:southcentralus",
        Gpt4OMini20240718Westus: "gpt-4o-mini-2024-07-18:westus",
        Gpt4OMini20240718Westus3: "gpt-4o-mini-2024-07-18:westus3",
        Gpt4OMini20240718Eastus: "gpt-4o-mini-2024-07-18:eastus",
        Gpt4OMini20240718Eastus2: "gpt-4o-mini-2024-07-18:eastus2",
        Gpt4OMini20240718Northcentralus: "gpt-4o-mini-2024-07-18:northcentralus",
        Gpt4OMini20240718Southcentralus: "gpt-4o-mini-2024-07-18:southcentralus",
        Gpt4O20240513Eastus2: "gpt-4o-2024-05-13:eastus2",
        Gpt4O20240513Eastus: "gpt-4o-2024-05-13:eastus",
        Gpt4O20240513Northcentralus: "gpt-4o-2024-05-13:northcentralus",
        Gpt4O20240513Southcentralus: "gpt-4o-2024-05-13:southcentralus",
        Gpt4O20240513Westus3: "gpt-4o-2024-05-13:westus3",
        Gpt4O20240513Westus: "gpt-4o-2024-05-13:westus",
        Gpt4Turbo20240409Eastus2: "gpt-4-turbo-2024-04-09:eastus2",
        Gpt40125PreviewEastus: "gpt-4-0125-preview:eastus",
        Gpt40125PreviewNorthcentralus: "gpt-4-0125-preview:northcentralus",
        Gpt40125PreviewSouthcentralus: "gpt-4-0125-preview:southcentralus",
        Gpt41106PreviewAustralia: "gpt-4-1106-preview:australia",
        Gpt41106PreviewCanadaeast: "gpt-4-1106-preview:canadaeast",
        Gpt41106PreviewFrance: "gpt-4-1106-preview:france",
        Gpt41106PreviewIndia: "gpt-4-1106-preview:india",
        Gpt41106PreviewNorway: "gpt-4-1106-preview:norway",
        Gpt41106PreviewSwedencentral: "gpt-4-1106-preview:swedencentral",
        Gpt41106PreviewUk: "gpt-4-1106-preview:uk",
        Gpt41106PreviewWestus: "gpt-4-1106-preview:westus",
        Gpt41106PreviewWestus3: "gpt-4-1106-preview:westus3",
        Gpt40613Canadaeast: "gpt-4-0613:canadaeast",
        Gpt35Turbo0125Canadaeast: "gpt-3.5-turbo-0125:canadaeast",
        Gpt35Turbo0125Northcentralus: "gpt-3.5-turbo-0125:northcentralus",
        Gpt35Turbo0125Southcentralus: "gpt-3.5-turbo-0125:southcentralus",
        Gpt35Turbo1106Canadaeast: "gpt-3.5-turbo-1106:canadaeast",
        Gpt35Turbo1106Westus: "gpt-3.5-turbo-1106:westus",
    } as const;
}
