/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OrganizationMember {
    pk_user_id?: number;
    email?: string;
    name?: string;
    is_active?: boolean;
    role?: OrganizationMember.Role;
    joined_at?: string;
    /** Whether this organization is the user's primary org */
    is_default_org?: boolean;
}

export namespace OrganizationMember {
    export type Role = "owner" | "admin" | "manager" | "member";
    export const Role = {
        Owner: "owner",
        Admin: "admin",
        Manager: "manager",
        Member: "member",
    } as const;
}
