/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OrganizationStats {
    /** Total number of users in the organization */
    totalUsers?: number;
    /** Number of active users */
    activeUsers?: number;
    /** Total number of agents */
    totalAgents?: number;
    /** Total number of phone numbers */
    totalPhones?: number;
    /** Total number of knowledge assets */
    totalAssets?: number;
    /** Total number of calls made */
    totalCalls?: number;
}
