/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface OrganizationDetailed extends Sonyk.Organization {
    /** Current subscription tier */
    subscription_status?: OrganizationDetailed.SubscriptionStatus;
    /** Available credits (in seconds of call time) */
    credits_balance?: number;
    members?: Sonyk.OrganizationMember[];
    stats?: Sonyk.OrganizationStats;
}

export namespace OrganizationDetailed {
    /**
     * Current subscription tier
     */
    export type SubscriptionStatus = "free" | "pro" | "enterprise";
    export const SubscriptionStatus = {
        Free: "free",
        Pro: "pro",
        Enterprise: "enterprise",
    } as const;
}
