/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OrganizationMembership {
    id?: number;
    name?: string;
    subscription_status?: OrganizationMembership.SubscriptionStatus;
    credits_balance?: number;
    /** User's role in this organization */
    role?: OrganizationMembership.Role;
    /** Whether this is the user's primary organization */
    is_default?: boolean;
    joined_at?: string;
}

export namespace OrganizationMembership {
    export type SubscriptionStatus = "free" | "pro" | "enterprise";
    export const SubscriptionStatus = {
        Free: "free",
        Pro: "pro",
        Enterprise: "enterprise",
    } as const;
    /**
     * User's role in this organization
     */
    export type Role = "owner" | "admin" | "manager" | "member";
    export const Role = {
        Owner: "owner",
        Admin: "admin",
        Manager: "manager",
        Member: "member",
    } as const;
}
