/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Organization {
    /** Organization ID */
    pk_org_id?: number;
    /** Organization name */
    org_name?: string;
    org_email?: string;
    org_address?: string;
    tax_id?: string;
    is_active?: boolean;
    created_at?: string;
}
