/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface PaginatedResponse extends Sonyk.BaseResponse {
    meta?: PaginatedResponse.Meta;
}

export namespace PaginatedResponse {
    export interface Meta {
        pagination?: Meta.Pagination;
    }

    export namespace Meta {
        export interface Pagination {
            /** Current page number */
            currentPage?: number;
            /** Total number of pages */
            totalPages?: number;
            /** Total number of items */
            totalItems?: number;
            /** Number of items per page */
            itemsPerPage?: number;
        }
    }
}
