/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Phone {
    /** Unique phone identifier */
    pk_phone_id?: string;
    /** Phone number in E.164 format */
    phone_number?: string;
    /** Phone service provider */
    provider?: string;
    /** Optional friendly name for the phone */
    nickname?: string;
    /** Whether the phone is currently active */
    is_active?: boolean;
    /** ID of the assigned agent (if any) */
    fk_agent_id?: string;
    /** Organization that owns this phone */
    fk_org_id?: number;
    /** Phone creation timestamp */
    created_at?: string;
    /** Assigned agent details (if any) */
    agent?: Phone.Agent;
}

export namespace Phone {
    /**
     * Assigned agent details (if any)
     */
    export interface Agent {
        agent_id?: string;
        agent_name?: string;
    }
}
