/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface ProviderKeyResponse extends Sonyk.BaseResponse {
    data?: ProviderKeyResponse.Data;
}

export namespace ProviderKeyResponse {
    export interface Data {
        /** Provider identifier */
        provider?: string;
        /** Provider display name */
        provider_name?: string;
        /** Masked version of the API key */
        masked_key?: string;
        /** Action performed (for update/delete responses) */
        action?: Data.Action;
        /** Whether this provider has a key (for get responses) */
        has_key?: boolean;
    }

    export namespace Data {
        /**
         * Action performed (for update/delete responses)
         */
        export type Action = "updated" | "removed";
        export const Action = {
            Updated: "updated",
            Removed: "removed",
        } as const;
    }
}
