/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface ProviderStatusResponse extends Sonyk.BaseResponse {
    data?: ProviderStatusResponse.Data;
}

export namespace ProviderStatusResponse {
    export interface Data {
        /** List of configured provider names */
        configured_providers?: string[];
        /** Number of configured providers */
        total_configured?: number;
        /** List of all available provider names */
        available_providers?: string[];
    }
}
