/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ProviderKey {
    /** Masked version of the API key */
    masked_key?: string;
    /** Provider display name */
    provider_name?: string;
    /** Whether this provider has a key */
    has_key?: boolean;
}
