/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Provider {
    /** Provider identifier */
    id?: string;
    /** Provider display name */
    name?: string;
    /** Provider description */
    description?: string;
    /** Whether this provider has an API key configured */
    has_key?: boolean;
    /** Masked version of the API key (only if configured) */
    key_masked?: string;
}
