/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface ProvidersResponse extends Sonyk.BaseResponse {
    data?: ProvidersResponse.Data;
}

export namespace ProvidersResponse {
    export interface Data {
        providers?: Sonyk.Provider[];
        /** Total number of supported providers */
        total_providers?: number;
        /** Number of providers with configured keys */
        configured_providers?: number;
    }
}
