/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface ProviderKeysResponse extends Sonyk.BaseResponse {
    data?: ProviderKeysResponse.Data;
}

export namespace ProviderKeysResponse {
    export interface Data {
        /** Object containing masked provider keys */
        provider_keys?: Record<string, Sonyk.ProviderKey>;
        /** Number of configured providers */
        configured_count?: number;
        /** Last update timestamp */
        last_updated?: string;
    }
}
