/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface ProviderKeysUpdateResponse extends Sonyk.BaseResponse {
    data?: ProviderKeysUpdateResponse.Data;
}

export namespace ProviderKeysUpdateResponse {
    export interface Data {
        /** List of provider names that were updated */
        updated_providers?: string[];
        /** Total number of configured providers after update */
        total_configured?: number;
        /** Updated provider keys (masked) */
        provider_keys?: Record<string, Sonyk.ProviderKey>;
    }
}
