/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * sonyk language model configuration
 */
export interface SonykLlm {
    /**
     * Sonyk model to use:
     * - **sonyk-llm**: Cost effective, fast, good general performance
     */
    model: "sonyk-llm";
    /** **Most Important Setting**: This defines your agent's personality, knowledge, and behavior. */
    systemPrompt: string;
}
