/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Sonyk speech-to-text configuration
 */
export interface SonykStt {
    /**
     * Sonyk STT model :
     * - **sonyk-stt**: Latest, cost-effective (recommended)
     */
    model: "sonyk-stt";
    /**
     * Language code for speech recognition:
     * - **en**: English
     * - **es**: Spanish
     * - **fr**: French
     * - **de**: German
     * And many more...
     */
    language: string;
}
