/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Sonyk text-to-speech configuration
 */
export interface SonykTts {
    /**
     * Sonyk TTS models:
     * - **sonyk-tts**: High-quality TTS model
     */
    model: "sonyk-tts";
    /**
     * Sonyk TTS voice configuration:
     * - indigo-sonyk
     */
    voiceId: "indigo-sonyk";
}
