/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SuccessResponse {
    success?: boolean;
    /** Human-readable message describing the result */
    message: string;
    /** ISO 8601 timestamp of the response */
    timestamp: string;
}
