/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface SwitchOrganizationResponse extends Sonyk.BaseResponse {
    data?: SwitchOrganizationResponse.Data;
}

export namespace SwitchOrganizationResponse {
    export interface Data {
        organization?: Sonyk.OrganizationMembership;
        /** New JWT token with updated organization context */
        newToken?: string;
    }
}
