/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface Tool {
    /** Unique tool identifier */
    pk_tool_id?: string;
    /** Tool name (used as function name in agent calls) */
    tool_name?: string;
    /** Description of what the tool does */
    tool_description?: string;
    /** API endpoint URL that will be called */
    tool_endpoint?: string;
    /** HTTP method for the tool execution */
    tool_method?: Tool.ToolMethod;
    /** HTTP headers to include with requests */
    tool_headers?: Record<string, string>;
    /** Parameters that the tool accepts */
    parameters?: Sonyk.ToolParameter[];
    created_at?: string;
    fk_org_id?: number;
}

export namespace Tool {
    /**
     * HTTP method for the tool execution
     */
    export type ToolMethod = "GET" | "POST" | "PUT" | "DELETE";
    export const ToolMethod = {
        Get: "GET",
        Post: "POST",
        Put: "PUT",
        Delete: "DELETE",
    } as const;
}
