/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface Tool {
    /** Unique tool identifier */
    pk_tool_id?: string;
    /** Tool name (used as function name in agent calls) */
    tool_name?: string;
    /** Description of what the tool does */
    tool_description?: string;
    /** API endpoint URL that will be called */
    server_url?: string;
    /** Parameters that the tool accepts */
    parameters?: Sonyk.ToolParameter[];
    created_at?: string;
    fk_org_id?: number;
}
