/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ToolParameter {
    pk_param_id?: string;
    /** Parameter name */
    param_name?: string;
    /** Parameter data type */
    param_type?: ToolParameter.ParamType;
    /** Whether this parameter is required */
    is_required?: boolean;
    /** Description of the parameter */
    param_description?: string;
    default_value?: unknown;
    /** Validation rules for the parameter */
    validation_rules?: ToolParameter.ValidationRules;
}

export namespace ToolParameter {
    /**
     * Parameter data type
     */
    export type ParamType = "string" | "integer" | "number" | "boolean" | "array" | "object";
    export const ParamType = {
        String: "string",
        Integer: "integer",
        Number: "number",
        Boolean: "boolean",
        Array: "array",
        Object: "object",
    } as const;

    /**
     * Validation rules for the parameter
     */
    export interface ValidationRules {
        min?: number;
        max?: number;
        pattern?: string;
        enum?: string[];
    }
}
