/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UserProfile {
    /** User ID */
    id?: number;
    /** User's email address */
    email?: string;
    /** User's full name */
    name?: string;
    /** Derived username from email */
    username?: string;
    /** User's primary organization ID */
    defaultOrganizationId?: number;
}
