/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface UserProfileResponse extends Sonyk.BaseResponse {
    data?: Sonyk.UserProfile;
}
