/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../index.js";

export interface UserOrganizationsResponse extends Sonyk.BaseResponse {
    data?: UserOrganizationsResponse.Data;
}

export namespace UserOrganizationsResponse {
    export interface Data {
        user_id?: number;
        default_org_id?: number;
        organizations?: Sonyk.OrganizationMembership[];
    }
}
