/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface User {
    /** User ID */
    pk_user_id?: number;
    /** User's email address */
    email?: string;
    /** User's full name */
    name?: string;
    /** Whether the user account is active */
    is_active?: boolean;
    created_at?: string;
    country?: string;
    rank?: string;
}
