/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         provider_keys: {
 *             "openai": "your_openai_key_here",
 *             "groq": "your_groq_key_here",
 *             "deepgram": "your_deepgram_key_here",
 *             "anthropic": ""
 *         }
 *     }
 */
export interface SetProviderKeysRequest {
    /** Object containing provider keys to set/update */
    provider_keys: Record<string, string>;
}
