/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         api_key: "your_api_key_here"
 *     }
 */
export interface SetProviderKeyRequest {
    /** API key for the provider */
    api_key: string;
}
