/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         agentId: "ec2b396d-58e0-96f8-89af-f35908a8b36",
 *         toNumber: "+919831222222"
 *     }
 */
export interface InitiateCallRequest {
    /** UUID of the agent to use for the call */
    agentId: string;
    /** Phone number to call (E.164 format) */
    toNumber: string;
    /** Optional JSON object containing custom variables to pass to the agent during the call */
    variables?: Record<string, unknown>;
}
