/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { SonykClient } from "../../src/Client";

describe("Agents", () => {
    test("listAgents", async () => {
        const server = mockServerPool.createServer();
        const client = new SonykClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            meta: { pagination: { currentPage: 1, totalPages: 1, totalItems: 1, itemsPerPage: 1 } },
            data: [
                {
                    agent_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
                    agent_name: "Restaurant Receptionist",
                    agent_json: {
                        llm: {
                            model: "gpt-5",
                            systemPrompt:
                                "# Role\nYou are Georgia, a friendly and professional receptionist at the  restaurant.\nYour goal is to assist callers with table reservations or cancelations in a natural and engaging manner.\n\nRestaurant opening hours: 10 AM to 11 PM daily\nLocation: 24 Park Street\n\n# Tasks\n- Answer questions about the restaurant\n- Make table reservations\n- Cancel existing reservations\n- Provide information about menu and hours\n\n# Guidelines\n- Always be polite and professional\n- Confirm all reservation details\n- If you can't help, politely explain and offer alternatives\n",
                            provider: "openai",
                        },
                        stt: { model: "nova-3", language: "en", provider: "deepgram" },
                        tts: { model: "eleven_multilingual_v2", voiceId: "sarah", provider: "elevenlabs" },
                        name: "Georgia - Restaurant Receptionist",
                        firstMessage: "Hello! Welcome to  restaurant. I'm Georgia, how can I help you today?",
                        webhookUrl: "https://api.restaurant.com/webhook/call-ended",
                        callForwardNumber: "+xxxxxxxxxx",
                    },
                    created_at: "2024-01-15T09:30:00Z",
                    fk_org_id: 1,
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/api/developer/agents")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.listAgents();
        expect(response).toEqual({
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            meta: {
                pagination: {
                    currentPage: 1,
                    totalPages: 1,
                    totalItems: 1,
                    itemsPerPage: 1,
                },
            },
            data: [
                {
                    agent_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
                    agent_name: "Restaurant Receptionist",
                    agent_json: {
                        llm: {
                            provider: "openai",
                            model: "gpt-5",
                            systemPrompt:
                                "# Role\nYou are Georgia, a friendly and professional receptionist at the  restaurant.\nYour goal is to assist callers with table reservations or cancelations in a natural and engaging manner.\n\nRestaurant opening hours: 10 AM to 11 PM daily\nLocation: 24 Park Street\n\n# Tasks\n- Answer questions about the restaurant\n- Make table reservations\n- Cancel existing reservations\n- Provide information about menu and hours\n\n# Guidelines\n- Always be polite and professional\n- Confirm all reservation details\n- If you can't help, politely explain and offer alternatives\n",
                        },
                        stt: {
                            provider: "deepgram",
                            model: "nova-3",
                            language: "en",
                        },
                        tts: {
                            provider: "elevenlabs",
                            model: "eleven_multilingual_v2",
                            voiceId: "sarah",
                        },
                        name: "Georgia - Restaurant Receptionist",
                        firstMessage: "Hello! Welcome to  restaurant. I'm Georgia, how can I help you today?",
                        webhookUrl: "https://api.restaurant.com/webhook/call-ended",
                        callForwardNumber: "+xxxxxxxxxx",
                    },
                    created_at: "2024-01-15T09:30:00Z",
                    fk_org_id: 1,
                },
            ],
        });
    });

    test("createAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new SonykClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            agent_name: "Restaurant Receptionist",
            agent_json: {
                llm: {
                    model: "gpt-5",
                    systemPrompt:
                        "# Role\nYou are Georgia, a friendly and professional receptionist at the  restaurant.\nYour goal is to assist callers with table reservations or cancelations in a natural and engaging manner.\n\nRestaurant opening hours: 10 AM to 11 PM daily\nLocation: 24 Park Street\n\n# Tasks\n- Answer questions about the restaurant\n- Make table reservations\n- Cancel existing reservations\n- Provide information about menu and hours\n\n# Guidelines\n- Always be polite and professional\n- Confirm all reservation details\n- If you can't help, politely explain and offer alternatives\n",
                    provider: "openai",
                },
                stt: { model: "nova-3", language: "en", provider: "deepgram" },
                tts: { model: "eleven_multilingual_v2", voiceId: "sarah", provider: "elevenlabs" },
                name: "Georgia - Restaurant Receptionist",
                firstMessage: "Hello! Welcome to  restaurant. I'm Georgia, how can I help you today?",
            },
        };
        const rawResponseBody = {
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            data: {
                agent_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
                agent_name: "Restaurant Receptionist",
                agent_json: {
                    llm: {
                        model: "gpt-5",
                        systemPrompt:
                            "# Role\nYou are Georgia, a friendly and professional receptionist at the  restaurant.\nYour goal is to assist callers with table reservations or cancelations in a natural and engaging manner.\n\nRestaurant opening hours: 10 AM to 11 PM daily\nLocation: 24 Park Street\n\n# Tasks\n- Answer questions about the restaurant\n- Make table reservations\n- Cancel existing reservations\n- Provide information about menu and hours\n\n# Guidelines\n- Always be polite and professional\n- Confirm all reservation details\n- If you can't help, politely explain and offer alternatives\n",
                        provider: "openai",
                    },
                    stt: { model: "nova-3", language: "en", provider: "deepgram" },
                    tts: { model: "eleven_multilingual_v2", voiceId: "sarah", provider: "elevenlabs" },
                    name: "Georgia - Restaurant Receptionist",
                    firstMessage: "Hello! Welcome to  restaurant. I'm Georgia, how can I help you today?",
                    webhookUrl: "https://api.restaurant.com/webhook/call-ended",
                    callForwardNumber: "+xxxxxxxxxx",
                    structuredDataSchema: { tags: ["tags"], call_type: "Reservation", call_summary: "call_summary" },
                },
                created_at: "2024-01-15T09:30:00Z",
                fk_org_id: 1,
            },
        };
        server
            .mockEndpoint()
            .post("/api/developer/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.createAgent({
            agent_name: "Restaurant Receptionist",
            agent_json: {
                llm: {
                    provider: "openai",
                    model: "gpt-5",
                    systemPrompt:
                        "# Role\nYou are Georgia, a friendly and professional receptionist at the  restaurant.\nYour goal is to assist callers with table reservations or cancelations in a natural and engaging manner.\n\nRestaurant opening hours: 10 AM to 11 PM daily\nLocation: 24 Park Street\n\n# Tasks\n- Answer questions about the restaurant\n- Make table reservations\n- Cancel existing reservations\n- Provide information about menu and hours\n\n# Guidelines\n- Always be polite and professional\n- Confirm all reservation details\n- If you can't help, politely explain and offer alternatives\n",
                },
                stt: {
                    provider: "deepgram",
                    model: "nova-3",
                    language: "en",
                },
                tts: {
                    provider: "elevenlabs",
                    model: "eleven_multilingual_v2",
                    voiceId: "sarah",
                },
                name: "Georgia - Restaurant Receptionist",
                firstMessage: "Hello! Welcome to  restaurant. I'm Georgia, how can I help you today?",
            },
        });
        expect(response).toEqual({
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            data: {
                agent_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
                agent_name: "Restaurant Receptionist",
                agent_json: {
                    llm: {
                        provider: "openai",
                        model: "gpt-5",
                        systemPrompt:
                            "# Role\nYou are Georgia, a friendly and professional receptionist at the  restaurant.\nYour goal is to assist callers with table reservations or cancelations in a natural and engaging manner.\n\nRestaurant opening hours: 10 AM to 11 PM daily\nLocation: 24 Park Street\n\n# Tasks\n- Answer questions about the restaurant\n- Make table reservations\n- Cancel existing reservations\n- Provide information about menu and hours\n\n# Guidelines\n- Always be polite and professional\n- Confirm all reservation details\n- If you can't help, politely explain and offer alternatives\n",
                    },
                    stt: {
                        provider: "deepgram",
                        model: "nova-3",
                        language: "en",
                    },
                    tts: {
                        provider: "elevenlabs",
                        model: "eleven_multilingual_v2",
                        voiceId: "sarah",
                    },
                    name: "Georgia - Restaurant Receptionist",
                    firstMessage: "Hello! Welcome to  restaurant. I'm Georgia, how can I help you today?",
                    webhookUrl: "https://api.restaurant.com/webhook/call-ended",
                    callForwardNumber: "+xxxxxxxxxx",
                    structuredDataSchema: {
                        tags: ["tags"],
                        call_type: "Reservation",
                        call_summary: "call_summary",
                    },
                },
                created_at: "2024-01-15T09:30:00Z",
                fk_org_id: 1,
            },
        });
    });

    test("getAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new SonykClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            data: {
                agent_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
                agent_name: "Restaurant Receptionist",
                agent_json: {
                    llm: {
                        model: "gpt-5",
                        systemPrompt:
                            "# Role\nYou are Georgia, a friendly and professional receptionist at the  restaurant.\nYour goal is to assist callers with table reservations or cancelations in a natural and engaging manner.\n\nRestaurant opening hours: 10 AM to 11 PM daily\nLocation: 24 Park Street\n\n# Tasks\n- Answer questions about the restaurant\n- Make table reservations\n- Cancel existing reservations\n- Provide information about menu and hours\n\n# Guidelines\n- Always be polite and professional\n- Confirm all reservation details\n- If you can't help, politely explain and offer alternatives\n",
                        provider: "openai",
                    },
                    stt: { model: "nova-3", language: "en", provider: "deepgram" },
                    tts: { model: "eleven_multilingual_v2", voiceId: "sarah", provider: "elevenlabs" },
                    name: "Georgia - Restaurant Receptionist",
                    firstMessage: "Hello! Welcome to  restaurant. I'm Georgia, how can I help you today?",
                    webhookUrl: "https://api.restaurant.com/webhook/call-ended",
                    callForwardNumber: "+xxxxxxxxxx",
                    structuredDataSchema: { tags: ["tags"], call_type: "Reservation", call_summary: "call_summary" },
                },
                created_at: "2024-01-15T09:30:00Z",
                fk_org_id: 1,
                assets: [
                    {
                        pk_asset_id: 123,
                        fk_agent_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
                        title: "Product Documentation v2.1",
                        date_created: "2025-01-15T10:30:00Z",
                        is_active: true,
                        chunk_count: 23,
                    },
                ],
                phones: [{ pk_phone_id: "phone_abc123def456", phone_number: "+xxxxxxxxxx", provider: "twilio" }],
                tools: [
                    {
                        pk_tool_id: "tool_123abc456def",
                        tool_name: "make_reservation",
                        tool_description: "Creates a new restaurant reservation with specified details",
                        server_url: "https://api.restaurant.com/reservations",
                    },
                ],
            },
        };
        server
            .mockEndpoint()
            .get("/api/developer/agents/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.getAgent("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx");
        expect(response).toEqual({
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            data: {
                agent_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
                agent_name: "Restaurant Receptionist",
                agent_json: {
                    llm: {
                        provider: "openai",
                        model: "gpt-5",
                        systemPrompt:
                            "# Role\nYou are Georgia, a friendly and professional receptionist at the  restaurant.\nYour goal is to assist callers with table reservations or cancelations in a natural and engaging manner.\n\nRestaurant opening hours: 10 AM to 11 PM daily\nLocation: 24 Park Street\n\n# Tasks\n- Answer questions about the restaurant\n- Make table reservations\n- Cancel existing reservations\n- Provide information about menu and hours\n\n# Guidelines\n- Always be polite and professional\n- Confirm all reservation details\n- If you can't help, politely explain and offer alternatives\n",
                    },
                    stt: {
                        provider: "deepgram",
                        model: "nova-3",
                        language: "en",
                    },
                    tts: {
                        provider: "elevenlabs",
                        model: "eleven_multilingual_v2",
                        voiceId: "sarah",
                    },
                    name: "Georgia - Restaurant Receptionist",
                    firstMessage: "Hello! Welcome to  restaurant. I'm Georgia, how can I help you today?",
                    webhookUrl: "https://api.restaurant.com/webhook/call-ended",
                    callForwardNumber: "+xxxxxxxxxx",
                    structuredDataSchema: {
                        tags: ["tags"],
                        call_type: "Reservation",
                        call_summary: "call_summary",
                    },
                },
                created_at: "2024-01-15T09:30:00Z",
                fk_org_id: 1,
                assets: [
                    {
                        pk_asset_id: 123,
                        fk_agent_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
                        title: "Product Documentation v2.1",
                        date_created: "2025-01-15T10:30:00Z",
                        is_active: true,
                        chunk_count: 23,
                    },
                ],
                phones: [
                    {
                        pk_phone_id: "phone_abc123def456",
                        phone_number: "+xxxxxxxxxx",
                        provider: "twilio",
                    },
                ],
                tools: [
                    {
                        pk_tool_id: "tool_123abc456def",
                        tool_name: "make_reservation",
                        tool_description: "Creates a new restaurant reservation with specified details",
                        server_url: "https://api.restaurant.com/reservations",
                    },
                ],
            },
        });
    });

    test("updateAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new SonykClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            data: {
                agent_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
                agent_name: "Restaurant Receptionist",
                agent_json: {
                    llm: {
                        model: "gpt-5",
                        systemPrompt:
                            "# Role\nYou are Georgia, a friendly and professional receptionist at the  restaurant.\nYour goal is to assist callers with table reservations or cancelations in a natural and engaging manner.\n\nRestaurant opening hours: 10 AM to 11 PM daily\nLocation: 24 Park Street\n\n# Tasks\n- Answer questions about the restaurant\n- Make table reservations\n- Cancel existing reservations\n- Provide information about menu and hours\n\n# Guidelines\n- Always be polite and professional\n- Confirm all reservation details\n- If you can't help, politely explain and offer alternatives\n",
                        provider: "openai",
                    },
                    stt: { model: "nova-3", language: "en", provider: "deepgram" },
                    tts: { model: "eleven_multilingual_v2", voiceId: "sarah", provider: "elevenlabs" },
                    name: "Georgia - Restaurant Receptionist",
                    firstMessage: "Hello! Welcome to  restaurant. I'm Georgia, how can I help you today?",
                    webhookUrl: "https://api.restaurant.com/webhook/call-ended",
                    callForwardNumber: "+xxxxxxxxxx",
                    structuredDataSchema: { tags: ["tags"], call_type: "Reservation", call_summary: "call_summary" },
                },
                created_at: "2024-01-15T09:30:00Z",
                fk_org_id: 1,
            },
        };
        server
            .mockEndpoint()
            .put("/api/developer/agents/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.updateAgent("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx");
        expect(response).toEqual({
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            data: {
                agent_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
                agent_name: "Restaurant Receptionist",
                agent_json: {
                    llm: {
                        provider: "openai",
                        model: "gpt-5",
                        systemPrompt:
                            "# Role\nYou are Georgia, a friendly and professional receptionist at the  restaurant.\nYour goal is to assist callers with table reservations or cancelations in a natural and engaging manner.\n\nRestaurant opening hours: 10 AM to 11 PM daily\nLocation: 24 Park Street\n\n# Tasks\n- Answer questions about the restaurant\n- Make table reservations\n- Cancel existing reservations\n- Provide information about menu and hours\n\n# Guidelines\n- Always be polite and professional\n- Confirm all reservation details\n- If you can't help, politely explain and offer alternatives\n",
                    },
                    stt: {
                        provider: "deepgram",
                        model: "nova-3",
                        language: "en",
                    },
                    tts: {
                        provider: "elevenlabs",
                        model: "eleven_multilingual_v2",
                        voiceId: "sarah",
                    },
                    name: "Georgia - Restaurant Receptionist",
                    firstMessage: "Hello! Welcome to  restaurant. I'm Georgia, how can I help you today?",
                    webhookUrl: "https://api.restaurant.com/webhook/call-ended",
                    callForwardNumber: "+xxxxxxxxxx",
                    structuredDataSchema: {
                        tags: ["tags"],
                        call_type: "Reservation",
                        call_summary: "call_summary",
                    },
                },
                created_at: "2024-01-15T09:30:00Z",
                fk_org_id: 1,
            },
        });
    });

    test("deleteAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new SonykClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message", timestamp: "2024-01-15T09:30:00Z" };
        server
            .mockEndpoint()
            .delete("/api/developer/agents/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.deleteAgent("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx");
        expect(response).toEqual({
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
        });
    });

    test("getAgentTools", async () => {
        const server = mockServerPool.createServer();
        const client = new SonykClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            meta: { pagination: { currentPage: 1, totalPages: 1, totalItems: 1, itemsPerPage: 1 } },
            data: [
                {
                    pk_tool_id: "tool_123abc456def",
                    tool_name: "make_reservation",
                    tool_description: "Creates a new restaurant reservation with specified details",
                    server_url: "https://api.restaurant.com/reservations",
                    parameters: [
                        {
                            param_name: "reservation_date",
                            is_required: true,
                            param_description: "Date for the reservation in YYYY-MM-DD format",
                        },
                    ],
                    created_at: "2024-01-15T09:30:00Z",
                    fk_org_id: 1,
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/api/developer/agents/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/tools")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.getAgentTools("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx");
        expect(response).toEqual({
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            meta: {
                pagination: {
                    currentPage: 1,
                    totalPages: 1,
                    totalItems: 1,
                    itemsPerPage: 1,
                },
            },
            data: [
                {
                    pk_tool_id: "tool_123abc456def",
                    tool_name: "make_reservation",
                    tool_description: "Creates a new restaurant reservation with specified details",
                    server_url: "https://api.restaurant.com/reservations",
                    parameters: [
                        {
                            param_name: "reservation_date",
                            is_required: true,
                            param_description: "Date for the reservation in YYYY-MM-DD format",
                        },
                    ],
                    created_at: "2024-01-15T09:30:00Z",
                    fk_org_id: 1,
                },
            ],
        });
    });

    test("assignToolToAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new SonykClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { toolId: "tool_123abc456def" };
        const rawResponseBody = { success: true, message: "message", timestamp: "2024-01-15T09:30:00Z" };
        server
            .mockEndpoint()
            .post("/api/developer/agents/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/tools")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.assignToolToAgent("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx", {
            toolId: "tool_123abc456def",
        });
        expect(response).toEqual({
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
        });
    });

    test("unassignToolFromAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new SonykClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { toolId: "toolId" };
        const rawResponseBody = { success: true, message: "message", timestamp: "2024-01-15T09:30:00Z" };
        server
            .mockEndpoint()
            .delete("/api/developer/agents/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/tools")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.unassignToolFromAgent("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx", {
            toolId: "toolId",
        });
        expect(response).toEqual({
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
        });
    });
});
