/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { SonykClient } from "../../src/Client";

describe("Calls", () => {
    test("initiateCall", async () => {
        const server = mockServerPool.createServer();
        const client = new SonykClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            agentId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
            toNumber: "+xxxxxxxxxx",
            twilioSid: "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            twilioToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        };
        const rawResponseBody = {
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            data: {
                core_response: { key: "value" },
                call_tracking: {
                    call_id: "call_id",
                    agent_id: "agent_id",
                    to_number: "to_number",
                    initiated_at: "2024-01-15T09:30:00Z",
                    estimated_credits: 1,
                    available_credits: 1,
                },
                status_code: 1,
            },
        };
        server
            .mockEndpoint()
            .post("/api/developer/calls/initiate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.initiateCall({
            agentId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
            toNumber: "+xxxxxxxxxx",
            twilioSid: "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            twilioToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        });
        expect(response).toEqual({
            success: true,
            message: "message",
            timestamp: "2024-01-15T09:30:00Z",
            data: {
                core_response: {
                    key: "value",
                },
                call_tracking: {
                    call_id: "call_id",
                    agent_id: "agent_id",
                    to_number: "to_number",
                    initiated_at: "2024-01-15T09:30:00Z",
                    estimated_credits: 1,
                    available_credits: 1,
                },
                status_code: 1,
            },
        });
    });
});
