/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Agents } from "./api/resources/agents/client/Client.js";
import { Phones } from "./api/resources/phones/client/Client.js";
import { Tools } from "./api/resources/tools/client/Client.js";
import { Assets } from "./api/resources/assets/client/Client.js";
import { Calls } from "./api/resources/calls/client/Client.js";

export declare namespace SonykClient {
    export interface Options {
        environment?: core.Supplier<environments.SonykEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class SonykClient {
    protected readonly _options: SonykClient.Options;
    protected _agents: Agents | undefined;
    protected _phones: Phones | undefined;
    protected _tools: Tools | undefined;
    protected _assets: Assets | undefined;
    protected _calls: Calls | undefined;

    constructor(_options: SonykClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "sonyk-sdk",
                    "X-Fern-SDK-Version": "0.0.7",
                    "User-Agent": "sonyk-sdk/0.0.7",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get agents(): Agents {
        return (this._agents ??= new Agents(this._options));
    }

    public get phones(): Phones {
        return (this._phones ??= new Phones(this._options));
    }

    public get tools(): Tools {
        return (this._tools ??= new Tools(this._options));
    }

    public get assets(): Assets {
        return (this._assets ??= new Assets(this._options));
    }

    public get calls(): Calls {
        return (this._calls ??= new Calls(this._options));
    }
}
