/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SonykEnvironment = {
    Default: "https://api.sonyk.io",
} as const;

export type SonykEnvironment = typeof SonykEnvironment.Default;
